### ISSUE TITLE
python3.4 下，pip安装语法错误

### ISSUE THREAD

**Issue by dawei101** [PingPlusPlus/pingpp-python#8]
python3.4 下，pip安装语法错误

```
$ pip install pingpp
Collecting pingpp
  Using cached pingpp-2.0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1sooopwb/pingpp/setup.py", line 33, in <module>
        from pingpp.version import VERSION
      File "/tmp/pip-build-1sooopwb/pingpp/pingpp/__init__.py", line 14, in <module>
        from pingpp.resource import Charge
      File "/tmp/pip-build-1sooopwb/pingpp/pingpp/resource.py", line 53
        except KeyError, err:
                       ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1sooopwb/pingpp/
```

**Comment by dawei101** [comment]
@samurai00  你们不支持python3吗？

**Comment by duzhipeng** [comment]
> @samurai00 你们不支持python3吗？
同上，一样的问题，同样的报错信息。

**Comment by samurai00** [comment]
现在可以用 python3 了。
